services:
  chromadb:
    image: ghcr.io/chroma-core/chroma@sha256:1e0b73a187a28757c572acba508c46f48c9e8b0acaf5c20e6d95cdedce1acdf6 # was :latest (resolved 2026-09-29)
    container_name: chromadb
    restart: unless-stopped

    ports:
      - "127.0.0.1:8000:8000"

    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE

    volumes:
      - ./data:/chroma/chroma

    networks:
      - chroma-net

networks:
  chroma-net: